import java.util.Properties

/**
 * Version and build metadata generated by Gradle into `build-info.properties`.
 */
object AppBuildInfo {
    val version: String
    val buildDate: String

    init {
        val props = Properties()
        val stream = AppBuildInfo::class.java.getResourceAsStream("/build-info.properties")
        if (stream != null) {
            stream.use { props.load(it) }
        }
        version = props.getProperty("version", "dev")
        buildDate = props.getProperty("buildDate", "unknown")
    }

    fun displayLabel(): String = "Version $version  ·  Built $buildDate"
}
